/**
 * @codegen-generated
 *
 * This file is auto-generated by the codegen pipeline.
 * It can be safely deleted and regenerated.
 * Manual changes will be overwritten on next codegen run.
 *
 * To customize:
 * - Create a manual file in a different location
 * - Or add custom logic after codegen (files without this marker are preserved)
 */

import type { AuthRole } from "@workspace/supabase-auth/shared/auth-role"
import type { UserRoleDTO } from "@workspace/supabase-data/modules/user-roles/domain/dto/user-role.dto"

interface UserRoleRepository {
  findByUserId(userId: string): Promise<UserRoleDTO[]>
  replaceUserRoles(userId: string, roles: readonly AuthRole[]): Promise<UserRoleDTO[]>
}

export { type UserRoleRepository }
