/**
 * @codegen-generated
 *
 * This file is auto-generated by the codegen pipeline.
 * It can be safely deleted and regenerated.
 * Manual changes will be overwritten on next codegen run.
 *
 * To customize:
 * - Create a manual file in a different location
 * - Or add custom logic after codegen (files without this marker are preserved)
 */

import { z } from "zod"

const ProfileDTOSchema = z.object({
  avatarUrl: z.string().nullable(),
  createdAt: z.string(),
  email: z.string().email(),
  fullName: z.string().nullable(),
  updatedAt: z.string(),
  userId: z.string().uuid(),
})

type ProfileDTO = z.infer<typeof ProfileDTOSchema>

export { ProfileDTOSchema, type ProfileDTO }
