/**
 * @codegen-generated
 *
 * This file is auto-generated by the codegen pipeline.
 * It can be safely deleted and regenerated.
 * Manual changes will be overwritten on next codegen run.
 *
 * To customize:
 * - Create a manual file in a different location
 * - Or add custom logic after codegen (files without this marker are preserved)
 */

import { z } from "zod"

import { AUTH_ROLES } from "@workspace/supabase-auth/shared/auth-role"

const UserRoleDTOSchema = z.object({
  createdAt: z.string(),
  role: z.enum(AUTH_ROLES),
  userId: z.string().uuid(),
})

type UserRoleDTO = z.infer<typeof UserRoleDTOSchema>

export { UserRoleDTOSchema, type UserRoleDTO }
