/**
 * @codegen-generated
 *
 * This file is auto-generated by the codegen pipeline.
 * It can be safely deleted and regenerated.
 * Manual changes will be overwritten on next codegen run.
 *
 * To customize:
 * - Create a manual file in a different location
 * - Or add custom logic after codegen (files without this marker are preserved)
 */

import type { TypedSupabaseClient } from "@workspace/supabase-infra/types"

/**
 * Matches Postgres `public.auth_is_admin()` (JWT and/or `user_roles`), same as RLS.
 */
async function getAuthIsAdmin(supabase: TypedSupabaseClient) {
  const { data, error } = await supabase.rpc("auth_is_admin")

  if (error) {
    return { ok: false as const, error }
  }

  return { ok: true as const, isAdmin: Boolean(data) }
}

export { getAuthIsAdmin }
