// codegen:backend — do not hand-edit; regenerate with `pnpm codegen:backend --write`.

import { z } from "zod"

const looseCell = z.union([z.string(), z.number(), z.boolean(), z.null()])

const PsychologistPatientsDTOSchema = z.object({
  archivedAt: looseCell,
  archivedBy: looseCell,
  attachedDocuments: looseCell,
  clinicalHypothesis: looseCell,
  clinicalNotes: looseCell,
  createdAt: looseCell,
  createdBy: looseCell,
  currentMedications: looseCell,
  dataSharingConsent: looseCell,
  dataSharingConsentDate: looseCell,
  defaultSessionPrice: looseCell,
  deletedAt: looseCell,
  deletedBy: looseCell,
  dischargeReason: looseCell,
  disorders: looseCell,
  firstSessionDate: looseCell,
  id: looseCell,
  informedConsentDate: looseCell,
  informedConsentDocumentUrl: looseCell,
  informedConsentSigned: looseCell,
  initialComplaint: looseCell,
  inviteExpiresAt: looseCell,
  inviteReminderCount: looseCell,
  inviteReminderSentAt: looseCell,
  inviteSentVia: looseCell,
  inviteStatus: looseCell,
  inviteToken: looseCell,
  invitedAt: looseCell,
  isMinor: looseCell,
  knownAllergies: looseCell,
  lastSessionDate: looseCell,
  manualAddress: looseCell,
  manualCpf: looseCell,
  manualDateOfBirth: looseCell,
  manualDisplayName: looseCell,
  manualEmail: looseCell,
  manualEmergencyContacts: looseCell,
  manualFirstName: looseCell,
  manualFullName: looseCell,
  manualGender: looseCell,
  manualLastName: looseCell,
  manualPatientOrigin: looseCell,
  manualPhone: looseCell,
  manualPlaceOfBirth: looseCell,
  manualPreferredName: looseCell,
  manualProfession: looseCell,
  manualPronouns: looseCell,
  manualRg: looseCell,
  patientId: looseCell,
  preferredContactMethod: looseCell,
  priceSetAt: looseCell,
  priceSetBy: looseCell,
  psychologistId: looseCell,
  recoveryDeadline: looseCell,
  relationshipEndDate: looseCell,
  relationshipStartDate: looseCell,
  requiresLegalGuardian: looseCell,
  retentionUntil: looseCell,
  riskLevel: looseCell,
  status: looseCell,
  suicideRiskAssessment: looseCell,
  syncedAddress: looseCell,
  syncedCpf: looseCell,
  syncedDateOfBirth: looseCell,
  syncedDisplayName: looseCell,
  syncedEmail: looseCell,
  syncedFullName: looseCell,
  syncedGender: looseCell,
  syncedPhone: looseCell,
  syncedPlaceOfBirth: looseCell,
  syncedProfession: looseCell,
  syncedPronouns: looseCell,
  syncedRg: looseCell,
  therapeuticGoals: looseCell,
  totalSessionsCount: looseCell,
  treatmentPlan: looseCell,
  updatedAt: looseCell,
  updatedBy: looseCell,
})

type PsychologistPatientsDTO = z.infer<typeof PsychologistPatientsDTOSchema>

export { PsychologistPatientsDTOSchema, type PsychologistPatientsDTO }
