/**
 * @codegen-generated
 *
 * This file is auto-generated by the codegen pipeline.
 * It can be safely deleted and regenerated.
 * Manual changes will be overwritten on next codegen run.
 *
 * To customize:
 * - Create a manual file in a different location
 * - Or add custom logic after codegen (files without this marker are preserved)
 */

import { z } from "zod"

import { AUTH_ROLES } from "@workspace/supabase-auth/shared/auth-role"
import { AUTH_PERMISSIONS } from "@workspace/supabase-auth/shared/permission"

const UserAccessDTOSchema = z.object({
  accessVersion: z.number().int().nonnegative().nullable(),
  permissions: z.array(z.enum(AUTH_PERMISSIONS)),
  roles: z.array(z.enum(AUTH_ROLES)),
  subscription: z.record(z.string(), z.unknown()),
  userId: z.string().uuid(),
})

type UserAccessDTO = z.infer<typeof UserAccessDTOSchema>

export { UserAccessDTOSchema, type UserAccessDTO }
