/**
 * @codegen-generated
 *
 * This file is auto-generated by the codegen pipeline.
 * It can be safely deleted and regenerated.
 * Manual changes will be overwritten on next codegen run.
 *
 * To customize:
 * - Create a manual file in a different location
 * - Or add custom logic after codegen (files without this marker are preserved)
 */

import type { ProfileDTO } from "@workspace/supabase-data/modules/profiles/domain/dto/profile.dto"

interface ProfileRepository {
  findByUserId(userId: string): Promise<ProfileDTO | null>
}

export { type ProfileRepository }
