import {
  LOG_CORRELATION_ID_HEADER,
  LOG_CORRELATION_PROVENANCE_HEADER,
  LOG_REQUEST_URL_HEADER,
  LOG_TRACE_ID_HEADER,
} from "@workspace/logging/correlation"

export {
  LOG_CORRELATION_ID_HEADER,
  LOG_CORRELATION_PROVENANCE_HEADER,
  LOG_REQUEST_URL_HEADER,
  LOG_TRACE_ID_HEADER,
}
