#!/usr/bin/env tsx
/**
 * Phase 1: Deterministic Code Generator
 *
 * Consumes the semantic plan JSON (generated by Phase 0) and generates complete implementations
 *
 * Usage:
 *   pnpm tsx scripts/codegen/actions-fill-todos.ts --plan config/action-semantic-plan.json
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"

import { planRepositoryImportSpecifier } from "../../packages/codegen-tools/src/backend-codegen/plan-module-paths"
import type { ActionSemanticPlan } from "./actions-semantic-plan"

const repoRoot = resolve(process.cwd())

function toKebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
}

function toCamelCase(str: string): string {
  return toKebabCase(str).replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
}

function toPascalCase(str: string): string {
  const camel = toCamelCase(str)
  return camel.charAt(0).toUpperCase() + camel.slice(1)
}

function generateCompleteAction(plan: ActionSemanticPlan): string {
  const domainKebab = toKebabCase(plan.domainId)
  const tableKebab = toKebabCase(plan.table)
  const methodCamel = toCamelCase(plan.method)
  const repositoryClassName = `${toPascalCase(plan.table)}SupabaseRepository`
  const repositoryModule = domainKebab

  return `/**
 * ${toPascalCase(plan.method)}${toPascalCase(plan.table)} Server Action
 * 
 * Handles ${plan.method} operation for ${plan.table}.
 * 
 * @module @workspace/supabase-data/actions/${domainKebab}/${tableKebab}-${methodCamel}
 * codegen:actions-fill-todos (generated)
 */
"use server"

import { z } from "zod"

import { requireAuth } from "@workspace/supabase-data/lib/auth/require-auth"
import { createServerAuthClient } from "@workspace/supabase-auth/server/create-server-auth-client"
import { ${repositoryClassName} } from "${planRepositoryImportSpecifier(repositoryModule, tableKebab)}"
import { logServerEvent } from "@workspace/logging/server"

${generateInputSchema(plan)}

/**
 * ${plan.actionName} Server Action
 * 
 * @param input - Action input
 */
export async function ${plan.actionName}(
  input: ${plan.inputSchema.typeName}
): Promise<${plan.outputSchema.returnType}> {
  const startedAt = Date.now()
  
  // 1. Auth check (SSOT via requireAuth)
  const claims = await requireAuth({
    action: "${methodCamel}_${tableKebab}",
  })

  const userId = claims.sub

  try {
    // 2. Validate input
    const validated = ${plan.inputSchema.typeName}Schema.parse(input)

    // 3. Create auth client + repository
    const supabase = await createServerAuthClient()
    const repository = new ${repositoryClassName}(supabase)
    
    // 4. Execute operation
    const result = await repository.${plan.repositoryCall.method}(${plan.repositoryCall.arguments.join(", ")})

    // 5. Log success
    await logServerEvent({
      actorId: userId,
      actorType: "user",
      component: "${domainKebab}.${tableKebab}.${methodCamel}",
      durationMs: Date.now() - startedAt,
      eventFamily: "action.lifecycle",
      eventName: "${methodCamel}_${tableKebab}_success",
      operation: "${plan.method}",
      operationType: "action",
      outcome: "success",
      service: "supabase-data",
    })

    // 6. Return result
    return result as ${plan.outputSchema.returnType}
  } catch (error) {
    // 7. Log error
    await logServerEvent({
      actorId: userId,
      actorType: "user",
      component: "${domainKebab}.${tableKebab}.${methodCamel}",
      durationMs: Date.now() - startedAt,
      eventFamily: "action.lifecycle",
      eventName: "${methodCamel}_${tableKebab}_failed",
      operation: "${plan.method}",
      operationType: "action",
      outcome: "failure",
      error,
      service: "supabase-data",
    })

    throw error
  }
}
`
}

function generateInputSchema(plan: ActionSemanticPlan): string {
  return `/**
 * Input schema for ${plan.actionName}
 */
const ${plan.inputSchema.typeName}Schema = ${plan.inputSchema.zodSchema}

/**
 * Input type for ${plan.actionName}
 */
export type ${plan.inputSchema.typeName} = z.infer<typeof ${plan.inputSchema.typeName}Schema>
`
}

// Main
if (import.meta.url === `file://${process.argv[1]}`) {
  const write = process.argv.includes("--write")
  const planPath =
    process.argv.find((_, i) => process.argv[i - 1] === "--plan") ??
    resolve(repoRoot, "config/action-semantic-plan.json")

  if (!existsSync(planPath)) {
    process.stderr.write("❌ action-semantic-plan.json not found\n")
    process.exit(1)
  }

  const plan = JSON.parse(readFileSync(planPath, "utf8")) as ActionSemanticPlan

  console.log(`📝 Generating complete actions from semantic plan...`)
  console.log(`   Plan: ${planPath}`)
  console.log(`   Actions: ${plan.actions.length}`)
  console.log("")

  let generated = 0
  const actionsDir = join(repoRoot, "packages/supabase-data/src/actions")

  for (const action of plan.actions) {
    const domainKebab = toKebabCase(action.domainId)
    const tableKebab = toKebabCase(action.table)
    const methodCamel = toCamelCase(action.method)

    const actionFile = join(actionsDir, domainKebab, `${tableKebab}-${methodCamel}.codegen.ts`)

    if (!write) {
      console.log(`Would generate: ${domainKebab}/${tableKebab}-${methodCamel}.codegen.ts`)
      generated++
      continue
    }

    mkdirSync(dirname(actionFile), { recursive: true })
    const completeCode = generateCompleteAction(action)
    writeFileSync(actionFile, completeCode, "utf8")
    generated++
    console.log(`✅ Generated: ${domainKebab}/${tableKebab}-${methodCamel}.codegen.ts`)
  }

  console.log("")
  console.log(`🎉 Generated ${generated} complete actions!`)
  console.log("")
  console.log("📝 Next steps:")
  console.log("   1. Review generated code for business logic accuracy")
  console.log("   2. Implement TODOs in schemas")
  console.log("   3. Run: pnpm typecheck")
  console.log("   4. Run: pnpm lint")
}

export { generateCompleteAction }
