#!/usr/bin/env tsx
/**
 * Mark auto-generated files with @codegen-generated header
 *
 * Usage:
 *   pnpm tsx scripts/codegen/mark-autogenerated-files.ts
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs"
import { resolve, dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, "..", "..") // scripts/codegen -> nextjs-template root

const MANUAL_PATTERNS = [
  "packages/supabase-data/src/actions/_shared/",
  "packages/supabase-data/src/actions/user-access/",
  "packages/supabase-data/src/actions/user-roles/",
  "packages/supabase-data/src/actions/profiles/",
  "packages/supabase-data/src/actions/example/",
  "tests/",
  "config/",
  "packages/supabase-infra/",
]

const CODEGEN_MARKER = `/**
 * @codegen-generated
 * 
 * This file is auto-generated by the codegen pipeline.
 * It can be safely deleted and regenerated.
 * Manual changes will be overwritten on next codegen run.
 * 
 * To customize:
 * - Create a manual file in a different location
 * - Or add custom logic after codegen (files without this marker are preserved)
 */

`

function isManualFile(filePath: string): boolean {
  return MANUAL_PATTERNS.some((pattern) => filePath.includes(pattern))
}

function hasMarker(filePath: string): boolean {
  if (!existsSync(filePath)) return false
  const content = readFileSync(filePath, "utf8")
  return content.includes("@codegen-generated")
}

function addMarker(filePath: string): void {
  const content = readFileSync(filePath, "utf8")

  if (content.includes("@codegen-generated")) {
    return
  }

  const newContent = CODEGEN_MARKER + content
  writeFileSync(filePath, newContent, "utf8")
}

// Main
if (import.meta.url === `file://${process.argv[1]}`) {
  const { readdirSync, statSync } = require("node:fs")

  console.log("🏷️  Marking auto-generated files...")
  console.log("")

  let marked = 0
  let skipped = 0

  const srcDir = join(repoRoot, "packages/supabase-data/src")

  function scanDir(dir: string) {
    const entries = readdirSync(dir, { withFileTypes: true })

    for (const entry of entries) {
      const fullPath = join(dir, entry.name)
      const relativePath = fullPath.replace(repoRoot + "/", "")

      if (isManualFile(relativePath)) {
        if (entry.isFile() && entry.name.endsWith(".ts")) {
          skipped++
        }
        continue
      }

      if (entry.name.startsWith(".") || entry.name === "node_modules") {
        continue
      }

      if (entry.isDirectory()) {
        scanDir(fullPath)
      } else if (entry.isFile() && entry.name.endsWith(".ts")) {
        if (!hasMarker(fullPath)) {
          addMarker(fullPath)
          marked++
          console.log(`  ✅ Marked: ${relativePath}`)
        }
      }
    }
  }

  scanDir(srcDir)

  console.log("")
  console.log("📊 Summary:")
  console.log(`   Marked: ${marked} files`)
  console.log(`   Skipped (manual): ${skipped} files`)
  console.log("")
  console.log("✅ Auto-generated files marked with @codegen-generated")
  console.log("")
  console.log("📝 Next steps:")
  console.log("   Run: bash scripts/codegen/clean-autogenerated.sh")
  console.log("   This will delete marked files, preserve manual files")
}

export { isManualFile, hasMarker, addMarker, CODEGEN_MARKER }
