#!/usr/bin/env tsx
/**
 * @deprecated Cleanup uses **only** the `*.codegen.*` filename pattern
 * (`pnpm codegen:clean`). Do not add `@codegen-generated` block comments to
 * route files into cleanup. Backend emits `// codegen:backend —` on module stubs;
 * actions/tests use `*.codegen.ts` / `*.codegen.test.ts`.
 *
 * This entrypoint is kept so `pnpm codegen:mark-autogenerated` fails loudly with
 * guidance instead of mutating the tree.
 */

if (import.meta.url === `file://${process.argv[1]}`) {
  console.log("")
  console.log("⚠️  codegen:mark-autogenerated is deprecated.")
  console.log("")
  console.log("   • Remove generated output: pnpm codegen:clean")
  console.log("   • Only files matching *.codegen.* under actions/tests are deleted.")
  console.log("   • Module stubs from codegen:backend use the first-line marker")
  console.log("     // codegen:backend — … (not @codegen-generated).")
  console.log("")
  process.exit(0)
}
