#!/bin/bash
# Full Codegen Pipeline — One Command
# 
# Usage:
#   bash scripts/codegen/run-full-pipeline.sh [--clean] [--domain <name>]
#
# Options:
#   --clean     Clean all auto-generated files first
#   --domain    Generate only specified domain (skip others)
#
# STEP 0: PREREQUISITES (MANDATORY - NEVER SKIP)
# Before running this pipeline, you MUST have:
#   1. packages/supabase-infra/src/types/database.types.ts (generated by Supabase CLI)
#   2. config/domain-map.json (semantic: tables → domains)
#   3. config/repository-plan.json (defines codegen scope + methods)
#   4. config/action-semantic-plan.json (blueprint for actions/hooks)
#
# If any are missing, the pipeline will FAIL with instructions.

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

CLEAN=false
DOMAIN=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --clean)
      CLEAN=true
      shift
      ;;
    --domain)
      DOMAIN="$2"
      shift 2
      ;;
    *)
      echo -e "${RED}Unknown option: $1${NC}"
      echo "Usage: bash scripts/codegen/run-full-pipeline.sh [--clean] [--domain <name>]"
      exit 1
      ;;
  esac
done

echo -e "${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║         FULL CODEGEN PIPELINE — Starting...              ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# ============================================================================
# STEP 0: PREREQUISITES (MANDATORY - NEVER SKIP)
# ============================================================================
echo -e "${YELLOW}Step 0: Prerequisites (MANDATORY - NEVER SKIP)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Before running this pipeline, you MUST have:"
echo "  1. database.types.ts (generated by Supabase CLI)"
echo "  2. domain-map.json (semantic: tables → domains)"
echo "  3. repository-plan.json (defines codegen scope + methods)"
echo "  4. action-semantic-plan.json (blueprint for actions/hooks)"
echo ""

# Check 0.1: database.types.ts
if [ ! -f "packages/supabase-infra/src/types/database.types.ts" ]; then
  echo -e "${RED}  ✗ MISSING: database.types.ts${NC}"
  echo -e "${YELLOW}  Run: pnpm supabase:types:local${NC}"
  echo ""
  echo -e "${RED}Pipeline cannot proceed without database.types.ts${NC}"
  exit 1
else
  echo -e "${GREEN}  ✓${NC} database.types.ts exists"
fi

# Check 0.2: domain-map.json
if [ ! -f "config/domain-map.json" ]; then
  echo -e "${RED}  ✗ MISSING: domain-map.json${NC}"
  echo -e "${YELLOW}  Run: cp config/domain-map.example.json config/domain-map.json${NC}"
  echo -e "${YELLOW}  Then edit to add your domains${NC}"
  echo ""
  echo -e "${RED}Pipeline cannot proceed without domain-map.json${NC}"
  exit 1
else
  echo -e "${GREEN}  ✓${NC} domain-map.json exists"
fi

# Check 0.3: repository-plan.json
if [ ! -f "config/repository-plan.json" ]; then
  echo -e "${RED}  ✗ MISSING: repository-plan.json${NC}"
  echo -e "${YELLOW}  Run: pnpm codegen:repository-plan:context${NC}"
  echo -e "${YELLOW}  Then edit to specify methods per table${NC}"
  echo ""
  echo -e "${RED}Pipeline cannot proceed without repository-plan.json${NC}"
  exit 1
else
  echo -e "${GREEN}  ✓${NC} repository-plan.json exists"
fi

# Check 0.4: action-semantic-plan.json
if [ ! -f "config/action-semantic-plan.json" ]; then
  echo -e "${RED}  ✗ MISSING: action-semantic-plan.json${NC}"
  echo -e "${YELLOW}  Run: pnpm codegen:actions-semantic-plan${NC}"
  echo ""
  echo -e "${RED}Pipeline cannot proceed without action-semantic-plan.json${NC}"
  exit 1
else
  echo -e "${GREEN}  ✓${NC} action-semantic-plan.json exists"
fi

echo ""
echo -e "${GREEN}  ✓ All prerequisites satisfied!${NC}"
echo ""

# Step 0.5: Clean (if requested)
if [ "$CLEAN" = true ]; then
  echo -e "${YELLOW}Step 0.5: Cleaning auto-generated files...${NC}"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  bash scripts/codegen/clean-autogenerated.sh
  echo ""
fi

# ============================================================================
# STEP 1: Backend Codegen (Modules Layer)
# ============================================================================
echo -e "${YELLOW}Step 1: Backend Codegen (Modules Layer)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [ -n "$DOMAIN" ]; then
  echo -e "${YELLOW}  Generating modules for domain: ${DOMAIN}${NC}"
  pnpm codegen:backend --write --domain "$DOMAIN"
else
  echo -e "${YELLOW}  Generating all modules...${NC}"
  pnpm codegen:backend --write
fi

echo -e "${GREEN}  ✓${NC} Modules generated"
echo ""

# ============================================================================
# STEP 2: Actions & Hooks Codegen (Application Layer)
# ============================================================================
echo -e "${YELLOW}Step 2: Actions & Hooks Codegen (Application Layer)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo -e "${YELLOW}  Generating Server Actions and TanStack Query hooks...${NC}"
pnpm codegen:actions-hooks --write

echo -e "${GREEN}  ✓${NC} Actions and hooks generated"
echo ""

# ============================================================================
# STEP 3: Generate Tests
# ============================================================================
echo -e "${YELLOW}Step 3: Generate Tests${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo -e "${YELLOW}  Generating action unit tests...${NC}"
pnpm codegen:generate-action-tests --write

echo -e "${YELLOW}  Generating hook unit tests...${NC}"
pnpm codegen:generate-hook-tests --write

echo -e "${GREEN}  ✓${NC} Tests generated"
echo ""

# ============================================================================
# STEP 4: Package Exports Update
# ============================================================================
echo -e "${YELLOW}Step 4: Package Exports Update${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo -e "${YELLOW}  Updating package.json exports...${NC}"
pnpm tsx scripts/codegen/update-supabase-data-exports.ts

echo -e "${GREEN}  ✓${NC} Exports updated"
echo ""

# ============================================================================
# STEP 5: Validation
# ============================================================================
echo -e "${YELLOW}Step 5: Validation${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo -e "${YELLOW}  Running typecheck...${NC}"
if pnpm typecheck; then
  echo -e "${GREEN}  ✓${NC} Typecheck passed"
else
  echo -e "${RED}  ✗${NC} Typecheck failed — see errors above"
fi

echo ""
echo -e "${YELLOW}  Running lint...${NC}"
if pnpm lint; then
  echo -e "${GREEN}  ✓${NC} Lint passed"
else
  echo -e "${RED}  ✗${NC} Lint failed — see errors above"
fi

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║         FULL CODEGEN PIPELINE — Complete! ✅             ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${GREEN}Summary:${NC}"
echo "  Actions: $(find packages/supabase-data/src/actions -mindepth 2 -type f -name '*.ts' | wc -l | xargs)"
echo "  Modules: $(find packages/supabase-data/src/modules -type f -name '*.ts' 2>/dev/null | wc -l | xargs)"
echo "  Hooks: $(find packages/supabase-data/src/hooks -type f -name '*.ts' 2>/dev/null | wc -l | xargs)"
echo "  Exports: $(grep -c '"./' packages/supabase-data/package.json || echo 0)"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Review generated code for business logic accuracy"
echo "  2. Implement TODOs in generated files"
echo "  3. Run: pnpm test"
echo "  4. Commit changes"
echo ""
